version: "3"
services:

  ############# Xqueue: external grading of Open edX problems
  xqueue:
    image: eidev/openedx-xqueue:hawthorn
    build:
      context: ./xqueue
    volumes:
      - ./config/xqueue:/openedx/config
      - ./data/xqueue:/openedx/data
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - edx

  xqueue_consumer:
    image: eidev/openedx-xqueue:hawthorn
    build:
      context: ./xqueue
    volumes:
      - ./config/xqueue:/openedx/config
      - ./data/xqueue:/openedx/data
    restart: unless-stopped
    # Run 12 workers per queue
    command: ./manage.py run_consumer 12
    depends_on:
      - mysql
    networks:
      - edx
networks:
  edx:
    external: true