version: "3"
services:

  ############# Notes: backend store for edX Student Notes
  notes:
    image: eidev/openedx-notes:hawthorn
    build:
      context: ./notes
    networks:
      default:
        aliases:
          - notes.openedx
    volumes:
      - ./config/notes:/openedx/config
      - ./data/notes:/openedx/data
    restart: unless-stopped
    networks:
      - edx
    depends_on:
      - mysql

networks:
  edx:
    external: true